# Default values for prometheus-statsd-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/statsd-exporter
  tag: v0.16.0
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

priorityClassName: ""

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP

webPort: 9102
udpPort: 9125
tcpPort: 9125

ingress:
  enabled: false
  annotations: {}
  hosts: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

statsdMappingConfig: |-
  defaults:
    timer_type: histogram
