apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dex
  name: dex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      serviceAccountName: dex
      containers:
      - image: quay.io/dexidp/dex:v2.25.0
        name: dex
        command: 
        - /usr/local/bin/dex
        - serve
        - /etc/dex/cfg/config.yaml        
        volumeMounts:
        - name: config
          mountPath: /etc/dex/cfg
        ports:
        ports:
        - name: http
          containerPort: 5556
          protocol: TCP
        - name: telemetry
          containerPort: 5558
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 1
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 1         
      volumes:
      - name: config
        secret:
          secretName: dex
          items:
          - key: dex-config.yaml
            path: config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: dex
spec:
  type: ClusterIP
  ports:
  - name: http-dex
    port: 80
    protocol: TCP
    targetPort: http
  - name: telemetry
    port: 5558
    targetPort: telemetry    
  selector:
    app: dex
