apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: repository-runner
spec:
  template:
    spec:
      repository: allanhung/vault-exporter
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: repository-runner-autoscaler
spec:
  scaleTargetRef:
    name: repository-runner
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
    repositoryNames:
    - allanhung/vault-exporter
