authSecret:
  create: true
  name: "controller-manager"
  ### GitHub PAT Configuration
  github_token: "xxxxxxxxxxxxxxxxxxxxxxxx"

image:
  repository: summerwind/actions-runner-controller
  actionsRunnerRepositoryAndTag: summerwind/actions-runner:latest

metrics:
  serviceMonitor: true
  serviceMonitorLabels:
    release: po
  proxy:
    image:
      tag: v0.11.0

githubWebhookServer:
  enabled: true
  secret:
    create: true
    name: "github-webhook-server"
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx-external
      kubernetes.io/tls-acme: "true"
    enabled: true
