authSecret:
  create: true
  name: "controller-manager"
  ### GitHub PAT Configuration
  github_token: "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"

metrics:
  serviceMonitor: true
  serviceMonitorLabels:
    release: po
