authSecret:
  create: true
  name: "controller-manager"
  ### GitHub PAT Configuration
  github_token: "xxxxxxxxxxxxxxxxxxxxxxxx"

metrics:
  serviceMonitor: true
  serviceMonitorLabels:
    release: po
