apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
  name: {{ template "proxysql.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.proxysql.admin.port }}
      protocol: TCP
      name: proxysql-admin
    - port: {{ .Values.mysql.port }}
      protocol: TCP
      name: proxysql-sql
  selector:
    {{- include "proxysql.matchLabels" . | nindent 8 }}
