apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argo-workflows-sso
  labels: {{- include "labels" . | nindent 4 }}
spec:
  backendType: vault
  kvVersion: 1
  data:
  - name: client-secret
    key: secret/k8s/{{ .Values.env }}
    property: argoSecret
  template:
    stringData:
      client-id: argo-{{ .Values.env }}-app
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argo-mysql-config
  labels: {{- include "labels" . | nindent 4 }}
spec:
  backendType: vault
  kvVersion: 2
  data:
  - name: username
    key: ${VAULTENV}/data/argo/workflow/mysql
    property: username
  - name: password
    key: ${VAULTENV}/data/argo/workflow/mysql
    property: password
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: argo-artifact-credential
  labels: {{- include "labels" . | nindent 4 }}
spec:
  backendType: vault
  kvVersion: 2
  data:
  - name: accessKey
    key: ${VAULTENV}/data/argo/workflow/artifact
    property: accessKey
  - name: secretKey
    key: ${VAULTENV}/data/argo/workflow/artifact
    property: secretKey
