image:
  repository: prom/blackbox-exporter
  tag: v0.19.0

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: po
    interval: 30s
    scrapeTimeout: 10s
    module: http_2xx

prometheusRule:
  enabled: true
  additionalLabels:
    app: kube-prometheus-stack
    release: po
