image:
  repository: prom/blackbox-exporter
  tag: v0.19.0
  # pullSecrets:
  #   - myRegistrKeySecretName

extraArgs:
  - "--log.level=debug"

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        preferred_ip_protocol: ipv4
        ip_protocol_fallback: false
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
    https_2xx:
      prober: http
      timeout: 5s
      http:
        preferred_ip_protocol: ipv4
        ip_protocol_fallback: false
        fail_if_not_ssl: true
    http_any:
      prober: http
      timeout: 5s
      http:
        preferred_ip_protocol: ipv4
        ip_protocol_fallback: false
        valid_status_codes:
        - 200
        - 404
    tcp_connect:
      prober: tcp
      timeout: 5s
      tcp:
        preferred_ip_protocol: ipv4
        ip_protocol_fallback: false

serviceMonitor:
  enabled: true
  defaults:
    labels:
      release: po
    interval: 30s
    scrapeTimeout: 10s
    module: http_2xx

prometheusRule:
  enabled: true
  additionalLabels:
    app: kube-prometheus-stack
    release: po
