image:
  repository: allanhung/blackbox-exporter

config:
  modules:
    http_2xx:
      prober: http
      timeout: 5s
      http:
        valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
        follow_redirects: true
        preferred_ip_protocol: "ip4"
        fail_if_body_matches_json:
        - '{.version.number}=7.0.0'
        fail_if_body_not_matches_json:
        - '{.version.number}=6.5.1'
