apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-access
  labels:
    app: {{ .Release.Name }}-github
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imageCredentials" . }}
