{{- if .Values.eventsource.github -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-access
  labels:
    app: {{ .Release.Name }}-github
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  token: {{ .Values.eventsource.github.apiToken | b64enc | quote }}
  {{- if .Values.eventsource.github.webHookSecret }}
  secret: {{ .Values.eventsource.github.webHookSecret | b64enc | quote }}
  {{- end }}
{{- end }}
