argo-events:
  enable: true

imageCredentials:
  registry: https://index.docker.io/v1/
  username: my-docker-username
  password: my-docker-password

eventsource:
  github:
    servicePort: 12000
    apiToken: my-api-token
    webHookSecret: testwebhook
    repos:
    - owner: allanhung
      repository: kaniko-demo
      events:
      - "*"
      insecure: false
      active: true
      contentType: json

webhook:
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  labels: {}
  tls: true

eventbus:
  replicas: 3
