apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-statsd-exporter.fullname" . }}-mapping-config
  labels:
    {{- include "prometheus-statsd-exporter.labels" . | nindent 4 }}
data:
  statsd-mapping.conf: |-
{{ .Values.statsdMappingConfig | indent 4 }}
