apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/

resources:
- secrets.yaml

patchesStrategicMerge:
- fluent-bit.yaml

configMapGenerator:
- name: fluent-bit-config
  behavior: merge
  files:
  - fluent-bit.conf
