replicaCount: 1
image:
  repository: quay.io/prometheusmsteams/prometheus-msteams
  tag: v1.4.1

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: po
    scrapeInterval: 30s

connectors:
  # in alertmanager, this will be used as http://prometheus-msteams:2000/alerts-dev-env
- alerts-dev-env: <my-dev-webhook-url>
  # in alertmanager, this will be used as http://prometheus-msteams:2000/alerts-staging-env
- alerts-staging-env: <my-staging-webhook-url>
  # in alertmanager, this will be used as http://prometheus-msteams:2000/alerts-prod-env
- alerts-prod-env: <my-prod-webhook-url>
