{{- $apiIsStable := eq (include "nessus.ingress.isStable" .) "true" -}}
{{- $pathType := .Values.ingress.pathType | default "Prefix" }}
{{- $serviceName := include "nessus.fullname" . }}
{{- $servicePort := .Values.service.port | default "80" }}
{{- $ingressSupportsPathType := eq (include "nessus.ingress.supportsPathType" .) "true" }}
{{- if and .Values.ingress.enabled .Values.service.enabled }}
apiVersion: {{ include "nessus.ingress.apiVersion" . }}
kind: Ingress
metadata:
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nessus.labels" . | nindent 4 }}
  name: {{ include "nessus.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if $apiIsStable }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.host  }}
      secretName: tls-{{ include "nessus.fullname" . }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}              
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
{{- end }}
