{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "nessus.labels" . | nindent 4 }}
  name: {{ include "nessus.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.secrets.data  }}
  {{- printf "%s: %s" $key (tpl (toYaml $value) $ | b64enc) | nindent 2 }}
{{- end -}}
{{- end -}}
