apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    metadata:
      annotations:
        ram.aliyuncs.com/role: external-dns    
    spec:
      containers:
      - name: external-dns
        args:
        - --source=service
        - --source=ingress
        - --domain-filter=subdomain.personal.com
        - --provider=alibabacloud
        - --registry=txt
        - --txt-owner-id=k8s
        - --alibaba-cloud-config-file=
        - --log-level=info
        - --interval=1m
        volumeMounts:
        - mountPath: /usr/share/zoneinfo
          name: hostpath
      volumes:
      - name: hostpath
        hostPath:
          path: /usr/share/zoneinfo
          type: Directory
