apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: statsd-exporter
    release: po
  name: statsd-exporter
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: web
    scrapeTimeout: 10s
  jobLabel: statsd-exporter
  selector:
    matchLabels:
      app.kubernetes.io/instance: statsd-exporter
