image:
  repository: prom/statsd-exporter
  # Overrides the image tag whose default is the chart appVersion.
  tag: "" 

serviceMonitor:
  enabled: true
  namespace: monitoring
  additionalLabels:
    release: po
