statsdMappingConfig: |-
  defaults:
    timer_type: histogram
  mappings:
    - match: vault.audit.file.*
      name: "vault_audit_file"
      labels:
        method: "$1"
    - match: vault.barrier.*
      name: "vault_barrier"
      labels:
        method: "$1"
    - match: vault.runtime.*
      name: "vault_runtime"
      labels:
        method: "$1"
    - match: vault.expire.*
      name: "vault_expire"
      labels:
        method: "$1"
    - match: vault.merkle_flushdirty
      name: "vault_merkle_flushdirty"
    - match: vault.merkle_savecheckpoint
      name: "vault_merkle_savecheckpoint"
    - match: vault.policy.*
      name: "vault_policy"
      labels:
        method: "$1"
    - match: logshipper.streamWALs.*
      name: "logshipper_streamWALs"
      labels:
        method: "$1"
    - match: replication.*
      name: "replication"
      labels:
        method: "$1"
    - match: vault.*.lock.*
      name: "vault_provider_lock"
      labels:
        provider: "1"
        method: "$2"
    - match: vault.consul.*
      name: "vault_consul"
      labels:
        method: "$1"
    - match: vault.*.expire.num_leases
      name: "vault_expire_num_leases"
      labels:
        host: "$1"
    - match: vault.*.runtime.free_count
      name: "vault_runtime_free_count"
      labels:
        host: "$1"
    - match: vault.*.runtime.heap_objects
      name: "vault_runtime_heap_objects"
      labels:
        host: "$1"
    - match: vault.*.runtime.malloc_count
      name: "vault_runtime_malloc_count"
      labels:
        host: "$1"
    - match: vault.*.runtime.num_goroutines
      name: "vault_runtime_num_goroutines"
      labels:
        host: "$1"
    - match: vault.*.runtime.total_gc_pause_ns
      name: "vault_runtime_total_gc_pause_ns"
      labels:
        host: "$1"
    - match: vault.*.runtime.total_gc_runs
      name: "vault_runtime_total_gc_runs"
      labels:
        host: "$1"
    - match: vault.*.runtime.gc_pause_ns
      name: "vault_runtime_gc_pause_ns"
      labels:
        host: "$1"
    - match: vault.route.*.*
      name: "vault_route"
      labels:
        method: "$1"
        path: "$2"
    - match: vault.*.runtime.sys_bytes
      name: "vault_runtime_sys_bytes"
      labels:
        pod: "$1"
    - match: vault.*.runtime.alloc_bytes
      name: "vault_runtime_totaloc_bytes"
      labels:
        pod: "$1"
    - match: vault.database.Initialize
      name: "vault_database_initialize_total"
    - match: vault.database.Initialize.error
      name: "vault_database_initialize_error_total"
    - match: vault.database.*.Initialize
      name: "vault_database_initialize"
      labels:
        database: "$1"
    - match: vault.database.*.Initialize.error
      name: "vault_database_initialize_error"
      labels:
        database: "$1"
    - match: vault.database.CreateUser
      name: "vault_database_user_create_total"
    - match: vault.database.CreateUser.error
      name: "vault_database_user_create_error_total"
    - match: vault.database.*.CreateUser
      name: "vault_database_user_create"
      labels:
        database: "$1"
    - match: vault.database.*.CreateUser.error
      name: "vault_database_user_create_error"
      labels:
        database: "$1"
    - match: vault.database.RenewUser
      name: "vault_database_user_renew_total"
    - match: vault.database.RenewUser.error
      name: "vault_database_user_renew_error_total"
    - match: vault.database.*.RenewUser
      name: "vault_database_user_renew"
      labels:
        database: "$1"
    - match: vault.database.*.RenewUser.error
      name: "vault_database_user_renew_error"
      labels:
        database: "$1"
    - match: vault.database.RevokeUser
      name: "vault_database_user_revoke_total"
    - match: vault.database.RevokeUser.error
      name: "vault_database_user_revoke_error_total"
    - match: vault.database.*.RevokeUser
      name: "vault_database_user_revoke"
      labels:
        database: "$1"
    - match: vault.database.*.RevokeUser.error
      name: "vault_database_user_revoke_error"
      labels:
        database: "$1"
    - match: vault.database.Close
      name: "vault_database_close_total"
    - match: vault.database.Close.error
      name: "vault_database_close_error_total"
    - match: vault.database.*.Close
      name: "vault_database_close"
      labels:
        database: "$1"
    - match: vault.database.*.Close.error
      name: "vault_database_close_error"
      labels:
        database: "$1"
    - match: vault.wal_persistwals
      name: "vault_wal_persistwals"
    - match: vault.wal_flushready
      name: "vault_wal_flushready"
