apiVersion: v1
kind: Pod
metadata:
  name: centos
spec:
  containers:
  - args:
    - tail
    - -f
    - /dev/null
    image: centos
    imagePullPolicy: Always
    name: centos
  nodeSelector:
    type: virtual-kubelet
  tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
