virtualNode:
  image:
    repository: registry-vpc.us-east-1.aliyuncs.com/acs/virtual-nodes-eci
    tag: v2.0.0.80-f9a46a994-aliyun

controller:
  image: registry-vpc.us-east-1.aliyuncs.com/acs/virtual-node-affinity-admission-controller
  imageTag: v1.0.0.1-aliyun
  imagePullPolicy: Always
  serviceAccount: vk-affinity-admission-controller

env:
  ALIYUN_CLUSTERID: my-cluster-id
  ALIYUN_RESOURCEGROUP_ID: my-resourcegroup-id
  ECI_REGION: us-east-1
  ECI_ACCESS_KEY=my-access-key
  ECI_SECRET_KEY=my-secret-key
