provisionDataStore:
  cassandra: true
  elasticsearch: false
  kafka: false

storage:
  type: cassandra
  cassandra:
    user: user
    usePassword: true
    password: password
    keyspace: jaeger_index

cassandra:
  image:
    repo: docker-proxy.mydomain.com/cassandra
    tag: 3.11.6
  persistence:
    enabled: true
    storageClass: topology-aware-cloud-efficiency
    accessMode: ReadWriteOnce
    size: 20Gi 

schema:
  image: docker-proxy.mydomain.com/jaegertracing/jaeger-cassandra-schema

ingester:
  image: docker-proxy.mydomain.com/jaegertracing/jaeger-ingester
  enabled: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: po

agent:
  image: docker-proxy.mydomain.com/jaegertracing/jaeger-agent
  enabled: true
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: po

collector:
  image: docker-proxy.mydomain.com/jaegertracing/jaeger-collector
  enabled: true
  service:
    zipkin:
      port: 9411
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      kubernetes.io/tls-acme: "true"
    hosts:
      - jaeger-collector.mydomain.com
    tls:
      - secretName: jaeger-collector.mydomain.com-tls
        hosts:
          - jaeger-collector.mydomain.com
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: po

query:
  image: docker-proxy.mydomain.com/jaegertracing/jaeger-query
  enabled: true
  oAuthSidecar:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.1.0
    enabled: false
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      kubernetes.io/tls-acme: "true"
    hosts:
      - jaeger-query.mydomain.com
    tls:
      - secretName: jaeger-query.mydomain.com-tls
        hosts:
          - jaeger-query.mydomain.com
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: po

spark:
  image: docker-proxy.mydomain.com/jaegertracing/spark-dependencies
  enabled: true
