image:
  repository: ghcr.io/dexidp/dex
  pullPolicy: "IfNotPresent"
  tag: master

grpc:
  enabled: false

service:
  ports:
    http:
      port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"

config:
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: info
  web:
    http: 0.0.0.0:5556
  telemetry:
    http: 0.0.0.0:5558    
  oauth2:
    alwaysShowLoginScreen: false
    responseTypes: ["code", "token", "id_token"]
    skipApprovalScreen: true
  enablePasswordDB: false
