ingress:
  hosts:
    - host: dex.my-domain.com
      paths:
        - path: /
  tls:
    - secretName: dex.my-domain.com-tls
      hosts:
        - dex.my-domain.com

config:
  issuer: https://dex.my-domain.com
  logger:
    level: info
  connectors:
  - type: oidc
    id: oidc
    name: Okta
    config:
      issuer: https://my-okta.okta.com
      clientID: client-id
      clientSecret: client-secret
      redirectURI:  https://dex.my-domain.com/callback
      insecureSkipEmailVerified: true      
      insecureEnableGroups: true
      getUserInfo: true
      scopes:
      - profile
      - email
      - groups
      - offline_access
  staticClients:
  - id: gangway-app
    redirectURIs:
    - https://gangway.my-domain.com/callback
    name: 'Gangway'
    secret: gangway-secret
  - id: grafana-app
    redirectURIs:
    - https://grafana.my-domain.com/login/generic_oauth
    name: 'Grafana'
    secret: grafana-secret    
  - id: kiali-app
    redirectURIs:
    - https://kiali.my-domain.com/kiali
    name: 'Kiali'
    secret: kiali-secret
