image:
  repository: justwatch/elasticsearch_exporter
  tag: 1.1.0

serviceMonitor:
  enabled: true
  labels:
    release: po

prometheusRule:
  enabled: false
  labels:
    app: kube-prometheus-stack
    release: po
  rules: [] 
