apiVersion: v1
kind: Service
metadata:
  labels:
    service: spark-application-monitor
  name: spark-application-monitor
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: metrics
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    sparkoperator.k8s.io/launched-by-spark-operator: "true"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: po
  name: spark-application-monitor
spec:
  selector:
    matchLabels:
      service: spark-application-monitor
  namespaceSelector:
    matchNames:
    - spark
  endpoints:
  - interval: 5s
    port: metrics
    scheme: http
