apiVersion: v1
kind: Endpoints
metadata:
  name: bitbucket
  labels:
    app: bitbucket
subsets:
- addresses:
  - ip: 10.20.1.49
  ports:
  - name: http
    port: 7999
    protocol: TCP
  - name: https
    port: 7990
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: bitbucket
  labels:
    app: bitbucket
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7999
    protocol: TCP
    targetPort: 7999
  - name: https
    port: 7990
    protocol: TCP
    targetPort: 7990
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
  name: bitbucket
  namespace: infra
spec:
  ingressClassName: nginx-external
  rules:
  - host: bitbucket.int.quid.com
    http:
      paths:
      - backend:
          service:
            name: bitbucket
            port:
              number: 7999
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bitbucket.int.quid.com
    secretName: tls-mbitbucket.int.quid.com
