# Overrides the chart's name
nameOverride: null

# Overrides the chart's computed fullname
fullnameOverride: null

kubeVersionOverride: null

# Number of replicas for the pod
replicas: 1

# The number of old replicaSets to retain to allow rollback
revisionHistoryLimit: 2

# Annotations for the pod
podAnnotations: {}

# The name of the ServiceAccount to use for the pod
serviceAccountName: ""
#serviceAccountName: '{{ include "subspace.fullname" . }}'

# Image pull secrets for docker images
imagePullSecrets: 
- name: regsecret

# Pod anti-affinity
affinity: {}

# Tolerations for the pod
tolerations: []

# Node selector for the pod
nodeSelector: {}

# SecurityContext for the pod
podSecurityContext: {}

image:
  # Docker image registry for the image
  registry: null
  # Docker image repository for the image
  repository: allanhung/subspace
  # Docker image tag for the image
  tag: null
  # Docker image pull policy
  pullPolicy: Always

# Configures the liveness probe for the container
livenessProbe: {}

# Configures the readiness probe for the container
readinessProbe: {}

# Define command for the container
command: []

# Define arguments for the container
args: []

# The SecurityContext for the container
containerSecurityContext: 
  privileged: true

# Environment variables to add to the pod (key: value)
env: 
  SUBSPACE_ALLOWED_IPS: 10.99.97.0/24,10.0.0.0/8
  SUBSPACE_DISABLE_DNS: '1'
  SUBSPACE_ENDPOINT_HOST: myip
  SUBSPACE_HTTP_ADDR: :8080
  SUBSPACE_HTTP_HOST: subspace.mydomain.com
  SUBSPACE_HTTP_INSECURE: 'true'
  SUBSPACE_IPV4_GW: 10.99.97.1
  SUBSPACE_IPV4_POOL: 10.99.97.0/24
  SUBSPACE_IPV6_GW: fd00::10:97:1
  SUBSPACE_IPV6_NAT_ENABLED: '0'
  SUBSPACE_IPV6_POOL: fd00::10:97:0/64
  SUBSPACE_LETSENCRYPT: 'false'
  SUBSPACE_LISTENPORT: '51820'
  SUBSPACE_NAMESERVERS: 1.1.1.1,8.8.8.8

# Environment variables from secrets or configmaps to add to the pod
envFrom: []

# Volume mounts to add to the the pod
volumeMounts: 
- mountPath: /host/usr/src
  name: usr-src
- mountPath: /lib/modules
  name: lib-modules

# Resource requests and limits for the pod
resources: {}

# Volumes to add to the pod
volumes: 
- hostPath:
    path: /usr/src
  name: usr-src
- hostPath:
    path: /lib/modules
  name: lib-modules

config: ""

service: 
  enabled: true
  port: 80
  targetPort: 8080
  type: ClusterIP
  udp:
    enabled: true
    port: 51820
    type: LoadBalancer

ingress: 
  annotations:
    kubernetes.io/ingress.class: nginx-external
    kubernetes.io/tls-acme: 'true'
  enabled: true
  host: subspace.mydomain.com
  tls:
    enabled: true
