{{ if (eq .Values.storage.type "clickhouse") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jaeger.fullname" . }}-clickhouse
  labels:
    {{- include "jaeger.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.storage.clickhouse | b64enc }}
{{- end }}
