apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sa-my-service-account
spec:
  rules:
  - name: sa-my-service-account
    match:
      resources:
        kinds:
        - Namespace
        name: "test-*"
    generate:
      synchronize: true
      kind: ServiceAccount
      name: test-account
      namespace: "{{request.object.metadata.name}}"
      data: {}
