kind: ConfigMap
apiVersion: v1
metadata:
  name: eni-config
  namespace: kube-system
data:
  eni_conf: |
    {
      "version": "1",
      "max_pool_size": 5,
      "min_pool_size": 0,

  
      "credential_path": "/var/addon/token-config",
  

      "vswitches": {"us-east-1a":["vsw-0xih99b2xjaltvkjoj1t5"],"us-east-1b":["vsw-0xisbozecq4saxn2bs8ao"]},
      "eni_tags": {"ack.aliyun.com":"c93c9d3f82910449e9694724fb16a4f51"},
      "service_cidr": "172.22.192.0/18",
      "security_group": "sg-0xie283qzyoduvloq4m2",
      "vswitch_selection_policy": "ordered"
    }
  10-terway.conf: |
    {
      "name": "terway",
      "cniVersion": "0.3.0",
      "type": "terway"
    }
  disable_network_policy: "false"



---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: terway-eniip
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: terway-eniip
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        app: terway-eniip
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      hostPID: true
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      tolerations:
      - operator: "Exists"
      terminationGracePeriodSeconds: 0
      serviceAccountName: terway
      hostNetwork: true
      initContainers:
      - name: terway-init
        image: registry-vpc.us-east-1.aliyuncs.com/acs/terway:v1.0.10.390-g5f3c461-aliyun
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command: 
        - /bin/init.sh
        volumeMounts:
        - name: configvolume
          mountPath: /etc/eni
        - name: cni-bin
          mountPath: /opt/cni/bin/
        - name: cni
          mountPath: /etc/cni/net.d/
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /host
          name: host-root
      containers:
      - name: terway
        image: registry-vpc.us-east-1.aliyuncs.com/acs/terway:v1.0.10.390-g5f3c461-aliyun
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/terwayd", "-log-level", "info", "-daemon-mode", "ENIMultiIP"]
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAMESPACE
          valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        volumeMounts:
        - name: configvolume
          mountPath: /etc/eni
        - mountPath: /var/run/
          name: eni-run
        - mountPath: /opt/cni/bin/
          name: cni-bin
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /var/lib/cni/networks
          name: cni-networks
        - mountPath: /var/lib/cni/terway
          name: cni-terway
        - mountPath: /var/lib/kubelet/device-plugins
          name: device-plugin-path
        - name: addon-token
          mountPath: "/var/addon"
          readOnly: true
      - name: policy
        image: registry-vpc.us-east-1.aliyuncs.com/acs/terway:v1.0.10.390-g5f3c461-aliyun
        imagePullPolicy: IfNotPresent
        command: ["/bin/policyinit.sh"]
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DISABLE_POLICY
          valueFrom:
            configMapKeyRef:
              name: eni-config
              key: disable_network_policy
              optional: true
        - name: FELIX_TYPHAK8SSERVICENAME
          valueFrom:
            configMapKeyRef:
              name: eni-config
              key: felix_relay_service
              optional: true
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: CILIUM_K8S_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: CILIUM_CNI_CHAINING_MODE
          value: terway-chainer
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: "250m"
          limits:
            cpu: "1"
        livenessProbe:
          httpGet: null
          tcpSocket:
            port: 9099
            host: localhost
          periodSeconds: 10
          initialDelaySeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet: null
          tcpSocket:
            port: 9099
            host: localhost
          periodSeconds: 10
        volumeMounts:
        - mountPath: /lib/modules
          name: lib-modules
        - mountPath: /etc/cni/net.d
          name: cni
        - mountPath: /etc/eni
          name: configvolume
        # volumes use by cilium
        - mountPath: /sys/fs
          name: sys-fs
        - mountPath: /var/run/cilium
          name: cilium-run
        - mountPath: /host/opt/cni/bin
          name: cni-bin
        - mountPath: /host/etc/cni/net.d
          name: cni
          # Needed to be able to load kernel modules
        - mountPath: /run/xtables.lock
          name: xtables-lock
      volumes:
      - name: configvolume
        configMap:
          name: eni-config
          items:
          - key: eni_conf
            path: eni.json
          - key: 10-terway.conf
            path: 10-terway.conf
      - name: cni-bin
        hostPath:
          path: /opt/cni/bin
          type: "Directory"
      - name: cni
        hostPath:
          path: /etc/cni/net.d
      - name: eni-run
        hostPath:
          path: /var/run/
          type: "Directory"
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: cni-networks
        hostPath:
          path: /var/lib/cni/networks
      - name: cni-terway
        hostPath:
          path: /var/lib/cni/terway
      - name: device-plugin-path
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: "Directory"
      - name: host-root
        hostPath:
          path: /
          type: "Directory"
      - name: addon-token
        secret:
          secretName: addon.network.token
          items:
          - key: addon.token.config
            path: token-config
          optional: true
      # used by cilium
      # To keep state between restarts / upgrades
      - hostPath:
          path: /var/run/cilium
          type: DirectoryOrCreate
        name: cilium-run
      # To keep state between restarts / upgrades for bpf maps
      - hostPath:
          path: /sys/fs/
          type: DirectoryOrCreate
        name: sys-fs
        # To access iptables concurrently with other processes (e.g. kube-proxy)
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
