nameOverride: "kiali"
fullnameOverride: "kiali"

auth:
  openid:
    api_proxy: https://kiali-proxy.mydomain.com:443
    api_proxy_ca_data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZVRENDQkRpZ0F3SUJBZ0lTQTdiSGU0SFBvOThFRkFoWFpaRnYrU28rTUEwR0NTcUdTSWIzRFFFQkN3VUEKTURJeEN6QUpCZ05WQkFZVEFsVlRNUll3RkFZRFZRUUtFdzFNWlhRbmN5QkZibU55ZVhCME1Rc3dDUVlEVlFRRApFd0pTTXpBZUZ3MHlNVEF4TURZeU16TTRNVFZhRncweU1UQTBNRFl5TXpNNE1UVmFNQ1F4SWpBZ0JnTlZCQU1NCkdTb3ViWGwwY21GbVptbGpiV0Z1WVdkbGJXVnVkQzVqYjIwd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDMlo1Yit0RVJUYlFCWlRxTFpJNVJOQVJKc1E1Vy82a3Z1RVNmdUhnRnhLd2hvMWtBTwpzRlFZN0NwWkJCRFp4Ty9HcTM5NTBUUDNPSUpaaUpNbkVtbkJqYy9uYmxzSnFzSTZ4T0JLMGluN1lHRW42UnMzCloxMG1PdmJjZkcvRWNsdjArSUVVVFNCQXE3c1g0S3M4YWJkelpPZEFjWFVUVldQM0ludENjKy9vak9PaVpkQ1kKR04rVVdtMDBzVUYrOXR0OUwvNk9pYTNhdlJhbXZIR1BFYm9zdWNLbzY0QTdvbzlucEl5WWo2Y2twRkdMek0yMwp3aDA0ZFhiR2tFQ3c1QXlBdFdRV2VBTGNUYUhuZTVxdDhCZ3FtWGU4L0xuME5PcDVwUENOK0FONjRQMkxXdmgrClVIRHlsZjdDL1ljL1Qxd0JhSFlpY0pVaStVdlI4L0ZjQzdFQkFnTUJBQUdqZ2dKc01JSUNhREFPQmdOVkhROEIKQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01Bd0dBMVVkRXdFQgovd1FDTUFBd0hRWURWUjBPQkJZRUZQSHNjL2thVmFrb29FZkJ2enlaTUhnY2pxVXRNQjhHQTFVZEl3UVlNQmFBCkZCUXVzeGUzV0ZiTHJsQUpRT1lmcjUyTEZNTEdNRlVHQ0NzR0FRVUZCd0VCQkVrd1J6QWhCZ2dyQmdFRkJRY3cKQVlZVmFIUjBjRG92TDNJekxtOHViR1Z1WTNJdWIzSm5NQ0lHQ0NzR0FRVUZCekFDaGhab2RIUndPaTh2Y2pNdQphUzVzWlc1amNpNXZjbWN2TUQwR0ExVWRFUVEyTURTQ0dTb3ViWGwwY21GbVptbGpiV0Z1WVdkbGJXVnVkQzVqCmIyMkNGMjE1ZEhKaFptWnBZMjFoYm1GblpXMWxiblF1WTI5dE1Fd0dBMVVkSUFSRk1FTXdDQVlHWjRFTUFRSUIKTURjR0N5c0dBUVFCZ3Q4VEFRRUJNQ2d3SmdZSUt3WUJCUVVIQWdFV0dtaDBkSEE2THk5amNITXViR1YwYzJWdQpZM0o1Y0hRdWIzSm5NSUlCQXdZS0t3WUJCQUhXZVFJRUFnU0I5QVNCOFFEdkFIWUFsQ0M4SG83VmpXeUljeCtDCml5SXNEZEhhVFY1c1Q1UTlZZHRPTDFoTm9zSUFBQUYyMmtlZmdBQUFCQU1BUnpCRkFpRUF1ZjdEcEwxZGFsZHMKQTYyVTl6TEJ1ZldJWlNETTNMckszUlZjNWREdk5tc0NJRFZyMG9IaWpTbm5NRDZWU1cyTU10dXhyU2FsTlh6RwowZTJseVRRL3d1NmhBSFVBZlQ3eStJLy9pRlZvSk1MQXlwNVNpWGtyeFE1NENYOHVhcGRvbVg0aThOY0FBQUYyCjJrZWYrUUFBQkFNQVJqQkVBaUJxdjNJbUlaRDBpMEtHTi9xMUVIQnNxN0hmNUEydDcxaStkYzZFNFZ4aDNBSWcKRjVtYTRGbnM2OENwUXd2Wittb05NSXBQMUZsZGtDNnUyWE5WYStZU3Jxc3dEUVlKS29aSWh2Y05BUUVMQlFBRApnZ0VCQUlvQVZmNGYvSlg4Um1meDRSVlBwVXhOUjUyeW1yRTF6a2trdDB1K1htTDQrYmIvNHRTRWtqOU1wOE1HCmVGaVhVbnRLekZYaXd6S24wZVNHNFE4OWJRYlk2Q3I0cUlscUtycGlWb2d2Sk5lTjh6R3QvUkdrZDJRRWc5ajIKN1JxZDdja2Vvb1lvYVZnbW4yZ25wZzRFR1Y0dmhqcms1RGNUWVE0QllCS0xrMzhmcTh3ZHZlTEQ5VWU4dmQ4UApyZjFhQ3MzSWxlc2NlVDh6WmFrOE1lUVhyTlRrbE43WVdyM0Rxb0pRanVyVS8wNVN5UXFnVGlXckZTRnBRSk1YCmxGb1B5Q25pQkhFcTJJQVpDVHZwQWk2UVVsT2QyMVNreHB6bXRhQml2dzkrVm1LcU4vaXhJMyt3Zi9WcmRsdTEKcjBZZ0ltRFF5TVdCbUhMbjYwN3pvS1E5R2tBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlFWlRDQ0EwMmdBd0lCQWdJUVFBRjFCSU1VcE1naGpJU3BEQmJOM3pBTkJna3Foa2lHOXcwQkFRc0ZBREEvCk1TUXdJZ1lEVlFRS0V4dEVhV2RwZEdGc0lGTnBaMjVoZEhWeVpTQlVjblZ6ZENCRGJ5NHhGekFWQmdOVkJBTVQKRGtSVFZDQlNiMjkwSUVOQklGZ3pNQjRYRFRJd01UQXdOekU1TWpFME1Gb1hEVEl4TURreU9URTVNakUwTUZvdwpNakVMTUFrR0ExVUVCaE1DVlZNeEZqQVVCZ05WQkFvVERVeGxkQ2R6SUVWdVkzSjVjSFF4Q3pBSkJnTlZCQU1UCkFsSXpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXV3SVZLTXoyb0pUVER4THMKalZXU3cvaUM4Wm1tZWtLSXAxMG1xclVydWNWTXNhK09hL2wxeUtQWEQwZVVGRlUxVjR5ZXFLSTVHZldDUEVLcApUbTcxTzhNdTI0M0FzRnp6V1RqbjdjOXA4Rm9MRzc3QWxDUWxoL28zY2JNVDV4eXM0WnZ2MitRN1JWSkZscW5CClU4NDB5Rkx1dGE3dGo5NWdjT0tsVkt1MmJRNlhwVUEwYXl2VHZHYnJaalI4K211TGoxY3BtZmd3RjEyNmNtLzcKZ2NXdDBvWllQUmZINXdtNzhTdjNodHpCMm5GZDFFYmp6SzBsd1lpOFlHZDFaclB4R1BlaVhPWlQvenFJdGtlbAoveE1ZNnBnSmR6K2RVL25QQWVYMXBuQVhGSzlqcFArWnM1T2QzRk9uQnY1SWhSMmhhYTRsZGJzVHpGSUQ5ZTFSCm9ZdmJGUUlEQVFBQm80SUJhRENDQVdRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQU9CZ05WSFE4QkFmOEUKQkFNQ0FZWXdTd1lJS3dZQkJRVUhBUUVFUHpBOU1Ec0dDQ3NHQVFVRkJ6QUNoaTlvZEhSd09pOHZZWEJ3Y3k1cApaR1Z1ZEhKMWMzUXVZMjl0TDNKdmIzUnpMMlJ6ZEhKdmIzUmpZWGd6TG5BM1l6QWZCZ05WSFNNRUdEQVdnQlRFCnA3R2tleXh4K3R2aFM1QjEvOFFWWUlXSkVEQlVCZ05WSFNBRVRUQkxNQWdHQm1lQkRBRUNBVEEvQmdzckJnRUUKQVlMZkV3RUJBVEF3TUM0R0NDc0dBUVVGQndJQkZpSm9kSFJ3T2k4dlkzQnpMbkp2YjNRdGVERXViR1YwYzJWdQpZM0o1Y0hRdWIzSm5NRHdHQTFVZEh3UTFNRE13TWFBdm9DMkdLMmgwZEhBNkx5OWpjbXd1YVdSbGJuUnlkWE4wCkxtTnZiUzlFVTFSU1QwOVVRMEZZTTBOU1RDNWpjbXd3SFFZRFZSME9CQllFRkJRdXN4ZTNXRmJMcmxBSlFPWWYKcjUyTEZNTEdNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBTkJna3Foa2lHOXcwQgpBUXNGQUFPQ0FRRUEyVXpneWZXRWlEY3gyN3NUNHJQOGkydGlFbXhZdDBsK1BBSzNxQjhvWWV2TzRDNXo3MGtICmVqV0VIeDJ0YVBEWS9sYUJMMjEvV0tadU5UWVFISFBENWIxdFhnSFhibkw3S3FDNDAxZGs1VnZDYWRUUXN2ZDgKUzhNWGpvaHljOXo5L0cyOTQ4a0xqbUU2RmxoOWREWXJWWUE5eDJPK2hFUEdPYUVPYTFlZVB5bkJnUGF5dlVmTApxakJzdHpMaFdWUUxHQWtYWG1Ocys1Wm5QQnh6REpPTHhoRjJKSWJlUUFjSDVIMHRaclVsbzVaWXlPcUE3czlwCk81Yjg1bzNBTS9PSitDa3RGQlF0ZnZCaGNKVmQ5d3Zsd1Bzayt1eU95MkhJN21OeEtLZ3NCVHQzNzV0ZUEyVHcKVWRIa2hWTmNzQUtYMUg3R05OTE9FQURrc2Q4Nnd1b1h2Zz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client_id: kiali-client-app
    issuer_uri: https://dex.mydomain.com
    scopes:
    - openid
    - profile
    - email
    - groups
    username_claim: email
  strategy: "openid"

istio_namespace: istio-system
  
login_token:
  signing_key: "$(openssl rand -hex 16)"

external_services:
  custom_dashboards:
    enabled: true    
  istio:
    istio_status_enabled: true
    component_status:
      components:
      - app_label: istiod
        is_core: true
      - app_label: istio-ingress-internal
        is_core: true
      - app_label: istio-egressgateway
        is_core: false
      enabled: true
    config_map_name: "istio"
    envoy_admin_local_port: 15000
    istio_identity_domain: "svc.cluster.local"
    istio_injection_annotation: "sidecar.istio.io/inject"
    istio_sidecar_injector_config_map_name: "istio-sidecar-injector"
    istio_sidecar_annotation: "sidecar.istio.io/status"
    istiod_deployment_name: "istiod"
    url_service_version: http://istiod.istio-system:15014/version
  tracing:
    url: https://jaeger-query.mydomain.com
    in_cluster_url: http://jaeger-query.infra.svc
  grafana:
    auth:
      use_kiali_token: true
    component_status:
      namespace: infra
    url: https://grafana.mydomain.com
    in_cluster_url: http://po-grafana.infra.svc
  prometheus:
    component_status:
      namespace: istio-system
    url: http://po-kube-prometheus-stack-prometheus.infra.svc:9090

kubernetes_config:
  burst: 200
  cache_duration: 300
  cache_enabled: true
  cache_istio_types:
  - DestinationRule
  - Gateway
  - ServiceEntry
  - VirtualService
  cache_namespaces:
  - .*
  cache_token_namespace_duration: 10
  excluded_workloads:
  - CronJob
  - DeploymentConfig
  - Job

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
    kubernetes.io/tls-acme: "true"
  hosts:
    - kiali.mydomain.com
  tls:
    - secretName: kiali.mydomain.com-tls
      hosts:
        - kiali.mydomain.com      
