{{- if .Capabilities.APIVersions.Has "apps/v1/Deployment" }}
apiVersion: apps/v1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
  name: '{{ .Release.Name }}-regsecret-operator'
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regsecret-operator
  template:
    metadata:
      labels:
        app: regsecret-operator
    spec:
      containers:
      - env:
        - name: REGSECRET_OPERATOR_CONFIG
          valueFrom:
            secretKeyRef:
              key: config
              name: '{{ .Release.Name }}-regsecret-operator-config'
        image: mcasimir/regsecret-operator:latest
        name: regsecret-operator
      serviceAccount: '{{ .Release.Name }}-regsecret-operator'
