apiVersion: v1
data:
  config: {{ .Values.config | toJson | b64enc }}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
  name: '{{ .Release.Name }}-regsecret-operator-config'
  namespace: '{{ .Release.Namespace }}'
type: Opaque
