apiVersion: v1
kind: Pod
metadata:
  name: fluent-bit-debug
spec:
  nodeSelector:
    kubernetes.io/hostname: debug_host
  serviceAccountName: fluent-bit   
  containers:
  - name: fluent-bit
    image: allanhung/fluent-bit:1.4.5
    imagePullPolicy: Always
    command:
      - /fluent-bit/bin/fluent-bit
      - -c
      - /fluent-bit/etc/fluent-bit.conf
      - -e
      - /usr/lib/x86_64-linux-gnu/out_loki.so
    volumeMounts:
    - name: config
      mountPath: /fluent-bit/etc
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      mountPath: /var/lib/docker/containers
      readOnly: true
  terminationGracePeriodSeconds: 10
  volumes:
  - name: config
    configMap:
      name: fluent-bit-config-debug
  - name: varlog
    hostPath:
      path: /var/log
  - name: varlibdockercontainers
    hostPath:
      path: /var/lib/docker/containers
