apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: /
    prometheus.io/port: '{{ .Values.listenerPort }}'
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.Version }}'
    helm.sh/chart: '{{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}'
  name: '{{ .Release.Name }}-jmx-metrics'
  namespace: '{{ .Release.Namespace }}'
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: {{ .Values.listenerPort }}
      protocol: TCP
      targetPort: metrics
  selector:
    app: {{ .Release.Name }}-jmx-exporter
