replicaCount: 1

debug: false

image:
  repository: banzaicloud/vault-secrets-webhook

vaultEnv:
  repository: banzaicloud/vault-env

podDisruptionBudget:
  enabled: false


podsFailurePolicy: Fail
configmapFailurePolicy: Fail
secretsFailurePolicy: Fail

configMapMutation: true

# enable github action
customResourceMutations:
- RunnerDeployment
- Runner
