image:
  repository: quay.io/jetstack/kube-oidc-proxy
  tag: v0.3.0

extraArgs:
  v: 5

oidc:
  usernameClaim: email
  usernamePrefix: "oidc:"
  groupsClaim: groups
  groupsPrefix: "oidc:"

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
