tls:
  secretName: gangway-proxy.my-domain.com-tls

oidc:
  clientId: gangway-app
  issuerUrl: https://dex.my-domain.com

ingress:
  hosts:
    - host: gangway-proxy.my-domain.com
      paths:
      - /
  tls:
    - secretName: gangway-proxy.my-domain.com-tls
      hosts:
        - gangway-proxy.my-domain.com
