image:
  repository: quay.io/jetstack/kube-oidc-proxy
  tag: v0.3.0

oidc:
  usernameClaim: email
  usernamePrefix: "oidc:"
  groupsClaim: groups
  groupsPrefix: "oidc:"

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
