serviceMonitor:
  labels:
    release: po
  metricRelabelings:
  - separator: ;
    regex: (.*)
    targetLabel: instance
    replacement: exampledb
    action: replace

redisAddress: redis://my-example:6379
