rabbitmq:
  url: http://myrabbit:15672
  user: guest
  password: guest
  existingPasswordSecret: ~

prometheus:
  monitor:
    relabelings:
    - separator: ;
      regex: (.*)
      targetLabel: instance
      replacement: myrabbit-server
      action: replace
