image:
  repository: kbudde/rabbitmq-exporter
  tag: v0.29.0

rabbitmq:
  url: http://myrabbit:15672
  user: guest
  password: guest
  existingPasswordSecret: ~

prometheus:
  monitor:
    enabled: true
    additionalLabels:
      release: po
    interval: 15s
    namespace: []
  rules:
    enabled: false
    additionalLabels:
      app: kube-prometheus-stack
      release: po
    rules: []
