apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: kiali
    release: {{ .Release.Name }}
data:
  config.yaml: |
    istio_component_namespaces:
      grafana: {{ .Values.global.grafanaNamespace }}
      tracing: {{ .Values.global.telemetryNamespace }}
      istiod: {{ .Values.global.istioNamespace }}
      prometheus: {{ .Values.global.prometheusNamespace }}
    istio_namespace: {{ .Values.global.istioNamespace }}
    auth:
      strategy: {{ .Values.kiali.dashboard.auth.strategy }}
{{- if eq .Values.kiali.dashboard.auth.strategy "openid" }}
      openid:
{{- with .Values.kiali.dashboard.auth.openid }}
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
    deployment:
      accessible_namespaces: ['**']
    login_token:
{{- if .Values.kiali.dashboard.signing_key }}
      signing_key: {{ .Values.kiali.dashboard.signing_key }}
{{- else }}
      signing_key: {{ randAlphaNum 10 | quote }}
{{- end }}
    server:
      port: 20001
{{- if .Values.kiali.contextPath }}
      web_root: {{ .Values.kiali.contextPath }}
{{- end }}
    external_services:
      istio:
        url_service_version: http://istiod{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}.{{ .Values.global.istioNamespace }}:15014/version
      tracing:
        url: {{ .Values.kiali.dashboard.jaegerURL }}
        in_cluster_url: {{ .Values.kiali.dashboard.jaegerInClusterURL }}
      grafana:
        auth:
          use_kiali_token: true
        component_status:
          namespace: {{ .Values.global.grafanaNamespace }}
        url: {{ .Values.kiali.dashboard.grafanaURL }}
        in_cluster_url: {{ .Values.kiali.dashboard.grafanaInClusterURL }}
      prometheus:
        component_status:
          namespace: {{ .Values.global.prometheusNamespace }}
{{- if .Values.kiali.prometheusAddr}}
        url: {{ .Values.kiali.prometheusAddr}}
{{- else }}
{{- if .Values.global.prometheusNamespace }}
        url: http://prometheus.{{ .Values.global.prometheusNamespace }}:9090
{{ else }}
        url: http://prometheus:9090
{{- end }}
{{- end}}
{{- if .Values.kiali.security.enabled }}
    identity:
      cert_file: {{ .Values.kiali.security.cert_file }}
      private_key_file: {{ .Values.kiali.security.private_key_file }}
{{- end}}
