apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: postgres-secret
  literals:
  - POSTGRES_DB=testdb
  - POSTGRES_PASSWORD=pgadmin
- name: postgres-init
  files:
  - init.sql

configMapGenerator:
- name: postgres-config
  files:
  - postgres.conf
  - pg_hba.conf
  - ssl/ca.crt
  - ssl/server.crt
  - ssl/server.key

resources:
- namespace.yaml
- postgres.yaml
