kiali:
  dashboard:
    auth:
      strategy: openid
      openid:
        issuer_uri: https://dex.develop.in.quid.com
        client_id: gangway-ali-dev-app
        username_claim: email
        scopes:
        - "openid"
        - "profile"
        - "email"
        - "groups"
        api_proxy: https://kube-oidc-proxy.develop.in.quid.com
        api_proxy_ca_data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMzakNDQWNhZ0F3SUJBZ0lSQUtzUTFzYmQwaWRZNHR0Ly8zZVFOZGt3RFFZSktvWklodmNOQVFFTEJRQXcKQURBZUZ3MHlNREE1TVRjeE1ESXlORFJhRncweU1ERXlNVFl4TURJeU5EUmFNQUF3Z2dFaU1BMEdDU3FHU0liMwpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURkK25yNWI3ZS92YjhzUGtoWm1QVXB1UlhkU2dPeFBTTFZGbkpNCk9IbjFsR0dSWVBMZE94eHM0Z3VsNmpXUnhHT2JGMTdGVmc2SUZGOVZ2YldBMHlyZ1QyTTFWM3c5eU5HUDd1UTQKWXFLOS9uemNzMTVFL3Q0RmZHYytvRUU2Z2ZIL2xXVFRUU0RrZUR1VG1kRVlGRWZZVVFFNFVKZ2FPZUVVdFNLTwoxVFhMSmV5R1FXaFVvTnd2QWl0RzVKZWZlTGJjbzZIVzEwVHU5aHUwM3ZVWEx1SkQ0ZDJLdThWVFUwSU52ZTVoCkQvVEtlL2wwMWxjblJGOS84bCs4RTVVV2lnOHh6SFNTcEJmMEFUSjJ3ZEpwalFqWmNYWEJwOWo1RlZHdEpiMGEKRUFXcFJaNkhWUUVXaTlOTk5TcXhkU2NQSkpsendCZzZYNjZyMkl2NkhRbXhqUjBsQWdNQkFBR2pVekJSTUE0RwpBMVVkRHdFQi93UUVBd0lGb0RBTUJnTlZIUk1CQWY4RUFqQUFNREVHQTFVZEVRRUIvd1FuTUNXQ0kydDFZbVV0CmIybGtZeTF3Y205NGVTNWtaWFpsYkc5d0xtbHVMbkYxYVdRdVkyOXRNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUIKQVFCVUJDL3VmWVBUMkJPU3FPcENUYVhnMUhsZVNTS1UrZCtDSStOSVhXZlFRV1BPTTBCMHNkSC9jWnVDcUY1MgpaOHFIMGdXdU4venY3Z0V4cWtXcGFNRUZKOHI2OVpyOXZTOHZySDJBVEgwMHdIdVJZUlBtMURQYVFzNDVHQ2dxCkMrdi9MZmRSYjBwV3lqUkRGYWpyc3R2RXdLTGlZWnFnVk82a1g5RFAvUVVLSTJaTVJwaXh3QS96QzZXVFM3MDQKYlZGMG5NTGFVQmRnRUJISG0yYnJaOGFQRjBFTm5ESUE0R1JDeWI3c0pLQ0NEUGJsUElMZTQ1RDJKVnI4dzhqYgppS3Bab1lrWFArSUJJTy9neHU5KzRiZmZGek5WZ0cycTM4K2orekR6NE1uSnZkWWMrTk9qczFsQ3NSRSsrRzduClFqT0VtLzZneUJUS25Fa0w4ekVFRE1BVAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCiAgCg==
