kiali:
  imagePullSecrets:
  - regsecret
  dashboard:
    auth:
      strategy: openid
      openid:
        issuer_uri: https://dex.my-domain.com
        client_id: kiali-app
        username_claim: email
        scopes:
        - "openid"
        - "profile"
        - "email"
        - "groups"
        api_proxy: https://kiali-proxy.my-domain.com
        api_proxy_ca_data: "my-ca-data"
  env:
    LOG_LEVEL: info
    LOG_FORMAT: text
