injector:
  metrics:
    enabled: true
  image:
    repository: "hashicorp/vault-k8s"
    tag: "0.5.0"
  agentImage:
    repository: "vault"
    tag: "1.5.2"
  logLevel: "info"
  resources:
    requests:
      memory: 128Mi
      cpu: 10m
    limits:
      memory: 256Mi
      cpu: 250m  
server:
  image:
    repository: "vault"
    tag: "1.5.2"
  # https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
  updateStrategyType: "OnDelete"    
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-issuer
    hosts:
      - host: chart-example.local
    tls:
      - hosts:
          - chart-example.local    
        secretName: chart-example.local-tls
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
  auditStorage:
    enabled: false
    size: 10Gi
    storageClass: null
  dev:
    enabled: false    
  ha:
    enabled: false
ui:
  enabled: true    
