image:
  repository: gcr.io/heptio-images/gangway
  tag: v3.2.0

env:
  GANGWAY_CLUSTER_CA_PATH: /etc/trustca/ca.crt

gangway:
  tokenURL: "http://dex/token"

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
  path: /

extraVolumeMounts:
- name: trustca
  mountPath: /etc/trustca/
