apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "kube-janitor.labels" . | nindent 4 }}
  name: {{ include "kube-janitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "kube-janitor.labels" . | nindent 4 }}
  name: {{ include "kube-janitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - watch
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "kube-janitor.labels" . | nindent 4 }}
  name: {{ include "kube-janitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-janitor
subjects:
- kind: ServiceAccount
  name: {{ include "kube-janitor.fullname" . }}
  namespace: {{ .Release.Namespace }}
