{{- $fullname := include "halyard.fullname" . }}
{{- $apiVersion := include "halyard.ingress.apiVersion" . }}
{{- $labels := include "halyard.labels" . }}
{{- $apiIsStable := eq (include "halyard.ingress.isStable" .) "true" -}}
{{- $ingressSupportsPathType := eq (include "halyard.ingress.supportsPathType" .) "true" }}
{{- if .Values.ingressList }}
{{- range $index, $ingress := .Values.ingressList }}
{{- $pathType := $ingress.pathType | default "Prefix" }}
{{- $serviceName := $ingress.service.name | default $fullname }}
{{- $servicePort := $ingress.service.port | default "80" }}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  {{- with $ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- $labels | nindent 4 }}
  name: {{ $fullname }}-{{ $index }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- if $apiIsStable }}
  ingressClassName: {{ $ingress.ingressClassName }}
  {{- end }}
  {{- if $ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $ingress.host  }}
      secretName: {{ $ingress.tls.secretName | default (printf "%s-%s-%d" "tls" $fullname $index) }}
  {{- end }}
  rules:
    - host: {{ $ingress.host }}
      http:
        paths:
          - path: {{ $ingress.path | default "/" }}
            {{- if $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}              
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
              {{- end }}
{{- end }}
{{- end }}
