{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "halyard.labels" . | nindent 4 }}
  name: {{ include "halyard.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.portName | default "http" }}
    port: {{ .Values.service.port | default "80" }}
    targetPort: {{ .Values.service.targetPort | default .Values.service.port | default "80" }}
    protocol: TCP
    {{- with .Values.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    {{- include "halyard.matchLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
{{- end }}
