apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
  labels:
    app: kube-prometheus-stack
    release: po
  name: cluster-autoscaler.rules
spec:
  groups:
  - name: cluster-autoscaler.alerts
    rules:
    - alert: ClusterAutoScalerScaleUp
      expr: increase(cluster_autoscaler_scaled_up_nodes_total[1m]) > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        description: Scaling up {{ $value }} node(s)
        summary: Kube Cluster Autoscaler is scaling up
    - alert: ClusterAutoScalerScaleDown
      expr: increase(cluster_autoscaler_scaled_down_nodes_total[1m]) > 0
      for: 1m
      labels:
        severity: warning
      annotations:
        description: Scaling down {{ $value }} node(s)
        summary: Kube Cluster Autoscaler is scaling down
