kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: topology-aware-cloud-ssd
provisioner: alicloud/disk
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: cloud_ssd
  encrypted: "true"
  fstype: xfs
