grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false

promtail:
  enabled: true
  image:
    tag: 1.6.1
  serviceMonitor:
    enabled: true
    interval: ""
    additionalLabels:
      release: po
    annotations: {}    
  syslogService:
    enabled: true
    type: ClusterIP
    port: 1514

loki:
  enabled: true
  image:
    tag: 1.6.1
  persistence:
    enabled: false
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls: []
  serviceMonitor:
    enabled: true
    interval: ""
    additionalLabels:
      release: po
    annotations: {}  
