grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false

promtail:
  enabled: true
  image:
    tag: 2.1.0
  serviceMonitor:
    enabled: true
    interval: ""
    additionalLabels:
      release: po
    annotations: {}    
  syslogService:
    enabled: true
    type: ClusterIP
    port: 1514

loki:
  enabled: true
  image:
    tag: 2.1.0
  config:
    ingester:
      chunk_idle_period: 3m
      chunk_block_size: 262144
      chunk_retain_period: 1m
      max_transfer_retries: 0
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
    limits_config:
      enforce_metric_name: false
      max_entries_limit_per_query: 20000
      reject_old_samples: true
      reject_old_samples_max_age: 168h
    schema_config:
      configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v11
        index:
          prefix: index_
          period: 24h
    server:
      http_listen_port: 3100
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks
    chunk_store_config:
      max_look_back_period: 0s
    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s
    compactor:
      working_directory: /data/loki/boltdb-shipper-compactor
      shared_store: filesystem
  persistence:
    enabled: false
    accessModes:
    - ReadWriteOnce
    size: 10Gi
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    tls: []
  serviceMonitor:
    enabled: true
    interval: ""
    additionalLabels:
      release: po
    annotations: {}  
