{
 "title": "Kubernetes Kafka",
 "description": "Global Kafka dashboard running on Kubernetes. Support  Bitnami Kafka chart https://github.com/bitnami/charts/tree/master/bitnami/kafka ",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "broker",
    "query": "label_values(kafka_controller_kafkacontroller_activecontrollercount_value, instance)"
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of brokers",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Unclean leader election",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_controllerstats_uncleanleaderelectionspersec_count{instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Active controller status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value)"
    }
   ]
  },
  {
   "title": "In-sync replicas shrinks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrshrinkspersec_count{instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Under replicated partitions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_under_replicated_partition)"
    }
   ]
  },
  {
   "title": "Partition count",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value{instance=~\"$broker\"}"
    }
   ]
  },
  {
   "title": "Active controller",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_activecontrollercount_value == 1"
    }
   ]
  },
  {
   "title": "In-sync replicas expands",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "- sum(kafka_server_replicamanager_total_isrexpandspersec_count{instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Offline partitions count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount_value{instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Bytes rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_bytesinpersec_count{instance=~\"$broker\"} / kafka_server_brokertopicmetrics_total_bytesoutpersec_count{instance=~\"$broker\"}",
     "legendFormat": "Broker {{ instance }}"
    }
   ]
  },
  {
   "title": "Messages IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_total_messagesinpersec_oneminuterate{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }} {{ value }}"
    }
   ]
  },
  {
   "title": "Number of partitions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_partitioncount_value",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes IN",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesinpersec_count{instance=~\"$broker\"}[5m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Bytes OUT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_total_bytesoutpersec_count{instance=~\"$broker\"}[5m])",
     "legendFormat": "Broker {{ instance }}"
    }
   ]
  },
  {
   "title": "In-sync replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "- kafka_server_replicamanager_total_isrshrinkspersec_count{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "JVM memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{instance=~\"$broker\"}",
     "legendFormat": "used {{ instance }}"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max{instance=~\"$broker\"}",
     "legendFormat": "max {{ instance }}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{instance=~\"$broker\"} * 100",
     "legendFormat": "system {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{instance=~\"$broker\"} * 100",
     "legendFormat": "process {{ instance }}"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$broker\"}",
     "legendFormat": "Total memory {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_freephysicalmemorysize{instance=~\"$broker\"}",
     "legendFormat": "Free memory {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_totalswapspacesize{instance=~\"$broker\"}",
     "legendFormat": "Total SWAP  {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_freeswapspacesize{instance=~\"$broker\"}",
     "legendFormat": "Free SWAP  {{ instance }}"
    },
    {
     "expr": "java_lang_operatingsystem_committedvirtualmemorysize{instance=~\"$broker\"}",
     "legendFormat": "Committed virtual memory {{ instance }}"
    }
   ]
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemloadaverage{instance=~\"$broker\"}",
     "legendFormat": "System load average"
    },
    {
     "expr": "java_lang_operatingsystem_availableprocessors{instance=~\"$broker\"}",
     "legendFormat": "Available Processors"
    }
   ]
  },
  {
   "title": "Open file descriptor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_openfiledescriptorcount{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_totalphysicalmemorysize{instance=~\"$broker\"})"
    }
   ]
  },
  {
   "title": "Class loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_classloading_loadedclasscount{instance=~\"$broker\"}",
     "legendFormat": "Loaded {{ instance }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{instance=~\"$broker\"}",
     "legendFormat": "Total loaded {{ instance }}"
    },
    {
     "expr": "java_lang_classloading_loadedclasscount_total{instance=~\"$broker\"}",
     "legendFormat": "Unloaded {{ instance }}"
    },
    {
     "expr": "delta(java_lang_classloading_loadedclasscount{instance=~\"$broker\"}[5m])",
     "legendFormat": "Delta {{ instance }}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_threading_threadcount{instance=~\"$broker\"}",
     "legendFormat": "Current {{ instance }}"
    },
    {
     "expr": "java_lang_threading_daemonthreadcount{instance=~\"$broker\"}",
     "legendFormat": "Daemon {{ instance }}"
    },
    {
     "expr": "java_lang_threading_peakthreadcount{instance=~\"$broker\"}",
     "legendFormat": "Peak {{ instance }}"
    },
    {
     "expr": "java_lang_threading_totalstartedthreadcount{instance=~\"$broker\"}",
     "legendFormat": "Started total {{ instance }}"
    }
   ]
  },
  {
   "title": "Total CPUs",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(java_lang_operatingsystem_availableprocessors{instance=~\"$broker\"})"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{instance=~\"$broker\", request=\"Produce\"}",
     "legendFormat": "{{ instance }} produce"
    },
    {
     "expr": "kafka_network_requestmetrics_requestspersec_count{instance=~\"$broker\", request=\"FetchConsumer\"}",
     "legendFormat": "{{ instance }} fetch consumer"
    },
    {
     "expr": " kafka_network_requestmetrics_requestspersec_count{instance=~\"$broker\", request=\"FetchFollower\"}",
     "legendFormat": "{{ instance }} fetch follower"
    }
   ]
  },
  {
   "title": "Purgatory delayed fetch operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_delayedoperationpurgatory_numdelayedoperations_fetch_value{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Log size by broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 44 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_log_log_size) by(instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "All number of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_network_requestmetrics_requestspersec_count{instance=~\"$broker\"}) by (request)",
     "legendFormat": "{{ request }}"
    }
   ]
  },
  {
   "title": "Idle network processors",
   "type": "graph",
   "description": "The average fraction of time the network processors are idle",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_processor_idlepercent_value{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }} network processor {{ network_processor }}"
    }
   ]
  },
  {
   "title": "Idle request handler threads",
   "type": "graph",
   "description": "The average fraction of time the request handler threads are idle",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_total_requesthandleravgidlepercent_oneminuterate{instance=~\"$broker\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}