piVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: spinnaker-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: spinnaker
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
