controller:
  enableStatefulSet: true
  logFormat: json
  logLevel: info
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: po
    rules:
      enabled: true
      additionalLabels:
        release: po
      spec:
      - alert: ArgoAppMissing
        expr: |
          absent(argocd_app_info)
        for: 15m
        labels:
          severity: critical
        annotations:
          summary: "[ArgoCD] No reported applications"
          description: >
            ArgoCD has not reported any applications data for the past 15 minutes which
            means that it must be down or not functioning properly.  This needs to be
            resolved for this cloud to continue to maintain state.
      - alert: ArgoAppNotSynced
        expr: |
          argocd_app_info{sync_status!="Synced"} == 1
        for: 12h
        labels:
          severity: warning
        annotations:
          summary: "[{{`{{$labels.name}}`}}] Application not synchronized"
          description: >
            The application [{{`{{$labels.name}}`}} has not been synchronized for over
            12 hours which means that the state of this cloud has drifted away from the
            state inside Git.

dex:
  enabled: false

server:
  logFormat: json
  logLevel: info
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: po
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx-internal
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    https: true

repoServer:
  logFormat: json
  logLevel: info
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: po
  serviceAccount:
    create: true
    name: argocd-repo-server
  rbac:
    - apiGroups:
      - argoproj.io
      resources:
      - applications
      verbs:
      - get
      - list
      - watch
