apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: infra
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      containers:
      - name: nginx-demo
        image: nginx
        imagePullPolicy: Always
