apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  app: fluent-bit-logging

generatorOptions:
  disableNameSuffixHash: true

resources:
- ns.yaml
- fluent-bit.yaml
- fluent-sa.yml

configMapGenerator:
- name: fluent-bit-config
  files:
  - fluent-bit.conf
  - parsers.conf
  - kubernetes_metadata.lua
