serviceMonitor:
  additionalLabels:
    release: po
  metricRelabelings:
  - separator: ;
    regex: (.*)
    targetLabel: instance
    replacement: exampledb
    action: replace

mysql:
  db: ""
  host: "exampledb"
  param: ""
  pass: "password"
  port: 3306
  protocol: ""
  user: "exporter"
  existingSecret: false
