apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: human@personal.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        webhook:
          groupName: acme.alidns.com
          solverName: alidns-solver
          config:
            region: "us-east-1"
            accessTokenSecretRef:
              name: alidns-secrets
              key: access-token
            secretKeySecretRef:
              name: alidns-secrets
              key: secret-key
      selector:
        dnsZones:
        - subdomain.example.com
    - dns01:
        webhook:
          config:
            account: my-dnsimple-account
            tokenSecretRef:
              key: token
              name: cert-manager-webhook-dnsimple
          groupName: acme.neoskop.de
          solverName: dnsimple
      selector:
        dnsZones:
        - example.com
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: human@personal.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        webhook:
          groupName: acme.alidns.com
          solverName: alidns-solver
          config:
            region: "us-east-1"
            accessTokenSecretRef:
              name: alidns-secrets
              key: access-token
            secretKeySecretRef:
              name: alidns-secrets
              key: secret-key
      selector:
        dnsZones:
        - subdomain.example.com
    - dns01:
        webhook:
          config:
            account: my-dnsimple-account
            tokenSecretRef:
              key: token
              name: cert-manager-webhook-dnsimple
          groupName: acme.neoskop.de
          solverName: dnsimple
      selector:
        dnsZones:
        - example.com
